// CommuteWise - utils/logger.js
// Version: Production 1.0

import { supabase } from '../supabaseClient';

export const logAction = async (action, details) => {
  try {
    // getSession is faster than getUser as it checks local storage first
    const { data: { session }, error: authError } = await supabase.auth.getSession();
    
    if (authError) throw authError;

    const user = session?.user;

    if (user) {
      const { error: dbError } = await supabase.from('admin_logs').insert({
        admin_id: user.id,
        admin_email: user.email || 'Unknown', // Fallback if email is missing
        action: action,
        details: details,
        // created_at is usually auto-generated by Supabase, but you can force it here if needed
        // created_at: new Date().toISOString(), 
      });

      if (dbError) throw dbError;
    } else {
      console.warn("Attempted to log action but no active user found.");
    }
  } catch (error) {
    // In production, you might want to send this to a service like Sentry
    console.error("CRITICAL: Failed to write to Admin Logs:", error);
  }
};